# Generated by Django 5.0 on 2024-09-04 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitesale',
            name='forma_de_pagamento',
            field=models.CharField(choices=[('CRÉIDTO', 'C/C'), ('DÉBITO', 'C/D'), ('DINHEIRO', 'DH'), ('PIX', 'PIX')], default=datetime.datetime(2024, 9, 4, 13, 24, 51, 61371), max_length=100, verbose_name='Forma de Pagamento'),
            preserve_default=False,
        ),
    ]
