# Generated by Django 5.0 on 2024-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='COD')),
                ('dt_retired', models.DateTimeField(auto_now_add=True, verbose_name='Data de Retirada')),
                ('name_associate', models.CharField(max_length=255, verbose_name='Nome do Titular')),
                ('type_associate', models.CharField(choices=[('AGREGADO', 'AGREGADO(a)'), ('SINDICALIZADO', 'SINDICALIZADO(A)')], max_length=30, verbose_name='Tipo de Sócio')),
                ('name_guest', models.CharField(max_length=255, verbose_name='Nome do Convidado')),
                ('doc_guest', models.CharField(max_length=15, verbose_name='Documento do Convidado')),
                ('status_invite', models.CharField(choices=[('AGREGADO', 'AGREGADO(a)'), ('SINDICALIZADO', 'SINDICALIZADO(A)')], default='SOLICITADO', max_length=30, verbose_name='Status do Convite')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'ordering': ['dt_retired'],
            },
        ),
    ]
