# Generated by Django 5.0 on 2024-08-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_alter_invite_status_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status_invite',
            field=models.CharField(choices=[('RETIRADO', 'RETIRADO'), ('SOLICITADO', 'SOLICITADO')], default='SOLICITADO', max_length=30, verbose_name='Status do Convite'),
        ),
    ]
